import { Link } from 'react-router'
import { useEffect, useState } from 'react'
import { getIncidents, type IncidentPage } from '../api/incidents'
import { clearAccessToken } from '../auth/session'

export function IncidentsPage() {
  const [data, setData] = useState<IncidentPage>(); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [sortBy, setSortBy] = useState('CREATED_AT'); const [page, setPage] = useState(0); const [error, setError] = useState('')
  useEffect(() => { getIncidents(page, status, sortBy).then(setData).catch(reason => setError(reason.message)) }, [page, status, sortBy])
  const visible = data?.content.filter(item => `${item.title} ${item.description}`.toLowerCase().includes(query.toLowerCase())) ?? []
  const open = data?.content.filter(item => item.status === 'OPEN').length ?? 0; const resolved = data?.content.filter(item => item.status === 'RESOLVED').length ?? 0
  function changeStatus(value: string) { setStatus(value); setPage(0) }
  return <main><p>PULSE / COMMAND CENTER</p><h1>Incidents</h1><Link to="/login" onClick={clearAccessToken}>Sign out</Link><section className="metric-row"><article><span>Total incidents</span><strong>{data?.totalElements ?? 0}</strong></article><article><span>Open on this page</span><strong>{open}</strong></article><article><span>Resolved on this page</span><strong>{resolved}</strong></article></section><section className="filters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search this page" /><select value={status} onChange={event => changeStatus(event.target.value)}><option value="">All statuses</option><option>OPEN</option><option>ACKNOWLEDGED</option><option>RESOLVED</option></select><select value={sortBy} onChange={event => { setSortBy(event.target.value); setPage(0) }}><option value="CREATED_AT">Newest first</option><option value="TITLE">Title</option><option value="SEVERITY">Severity</option><option value="STATUS">Status</option></select></section>{error && <p>{error}</p>}<section className="incident-list">{visible.map(incident => <Link className="incident-card" key={incident.id} to={`/incidents/${incident.id}`}><div><strong className={`severity ${incident.severity.toLowerCase()}`}>{incident.severity}</strong><span className={`status ${incident.status.toLowerCase()}`}>{incident.status}</span></div><h2>{incident.title}</h2><p>{incident.description}</p><small>Created {new Date(incident.createdAt).toLocaleString()}</small></Link>)}</section><nav className="pagination"><button disabled={data?.first} onClick={() => setPage(current => current - 1)}>Previous</button><span>Page {(data?.page ?? 0) + 1} of {data?.totalPages ?? 1}</span><button disabled={data?.last} onClick={() => setPage(current => current + 1)}>Next</button></nav></main>
}
